//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: example_service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Escrow_ExampleServiceClient, then call methods of this protocol to make API calls.
public protocol Escrow_ExampleServiceClientProtocol {
  func ping(_ request: Escrow_Input, callOptions: CallOptions?) -> UnaryCall<Escrow_Input, Escrow_Output>
}

public final class Escrow_ExampleServiceClient: GRPCClient, Escrow_ExampleServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the escrow.ExampleService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Unary call to Ping
  ///
  /// - Parameters:
  ///   - request: Request to send to Ping.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func ping(_ request: Escrow_Input, callOptions: CallOptions? = nil) -> UnaryCall<Escrow_Input, Escrow_Output> {
    return self.makeUnaryCall(path: "/escrow.ExampleService/Ping",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol Escrow_ExampleServiceProvider: CallHandlerProvider {
  func ping(request: Escrow_Input, context: StatusOnlyCallContext) -> EventLoopFuture<Escrow_Output>
}

extension Escrow_ExampleServiceProvider {
  public var serviceName: String { return "escrow.ExampleService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "Ping":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.ping(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload`
extension Escrow_Input: GRPCProtobufPayload {}
extension Escrow_Output: GRPCProtobufPayload {}
